/*
 * This rename module will rename the verilog
 * module signal names generated by SpinalHDL.
 */

package lib

import spinal.core._
import spinal.lib._

trait RenameIO {
  
  // XXX why we need this line?
  this : Component =>

  def renameIO(): Unit = {

    // Avoid the "io_" prefix
    this.noIoPrefix()

    for (port <- this.getAllIo) {
      val newName = port.getName()
        //.replaceAll("(a?[wrb])_(payload_)?", "$1")

        // For Axi Stream, raw interface
        .replaceAll("_payload$", "_tdata")
        .replaceAll("_ready$", "_tready")
        .replaceAll("_valid$", "_tvalid")

        // For Axi Stream, Fragment Interface
        .replaceAll("_last$", "_tlast")
        .replaceAll("_payload_t", "_t")
        .replaceAll("_payload_fragment_t", "_t")
        .replaceAll("_payload_", "_")

        // Special rules
        //.replaceAll("_desc_tready$", "_desc_ready")
        //.replaceAll("_desc_tvalid$", "_desc_valid")

        // fragments
        //.replaceAll("_fragment$", "_tdata")

      port.setName(newName)
    }
    println(f"Xilinx: Rename ${this.getClass().getSimpleName}")
  }
}
